// ═══════════════════════════════════════════════════════════════════════
// DATA: ASSETS, MACRO EVENTS, SIGNAL DATABASE, INTER-ASSET CORRELATION
// ═══════════════════════════════════════════════════════════════════════

// ── ASSET UNIVERSE ──────────────────────────────────────────────────────
const ASSETS = [
  // Crypto
  {k:"BTC",    l:"Bitcoin",          cat:"Crypto"},
  {k:"ETH",    l:"Ethereum",         cat:"Crypto"},
  {k:"ALT",    l:"Altcoins (mayor)", cat:"Crypto"},
  {k:"BTCD",   l:"BTC Dominance",    cat:"Crypto"},
  // Forex Majors
  {k:"DXY",    l:"DXY (USD Index)",  cat:"Forex"},
  {k:"EURUSD", l:"EUR/USD",          cat:"Forex"},
  {k:"GBPUSD", l:"GBP/USD",          cat:"Forex"},
  {k:"USDJPY", l:"USD/JPY",          cat:"Forex"},
  {k:"AUDUSD", l:"AUD/USD",          cat:"Forex"},
  {k:"NZDUSD", l:"NZD/USD",          cat:"Forex"},
  {k:"USDCAD", l:"USD/CAD",          cat:"Forex"},
  {k:"USDCHF", l:"USD/CHF",          cat:"Forex"},
  // Commodities
  {k:"GOLD",   l:"Gold (XAU/USD)",   cat:"Komoditas"},
  {k:"SILVER", l:"Silver (XAG/USD)", cat:"Komoditas"},
  {k:"OIL",    l:"WTI Crude Oil",    cat:"Komoditas"},
  {k:"COPPER", l:"Copper",           cat:"Komoditas"},
  // Indices / Bonds (referensi konteks, tidak ditradingkan tapi penting)
  {k:"SPX",    l:"S&P 500",          cat:"Index"},
  {k:"VIX",    l:"VIX (Fear Index)", cat:"Index"},
  {k:"US10Y",  l:"US 10Y Yield",     cat:"Bonds"},
];

const ASSET_MAP = {};
ASSETS.forEach(a=>ASSET_MAP[a.k]=a);

const CATS = ["Crypto","Forex","Komoditas","Index","Bonds"];
const CAT_ORDER = {Crypto:0,Forex:1,Komoditas:2,Index:3,Bonds:4};

const DIR = {LONG:"LONG", SHORT:"SHORT", NEUTRAL:"NEUTRAL"};

// ── MACRO EVENT CALENDAR (recurring schedule reference) ────────────────
const MACRO_CALENDAR = [
  {
    id:"FOMC", name:"FOMC Rate Decision", freq:"~8x/tahun (6 minggu)",
    time:"19:00 WIB (Rabu)", source:"Federal Reserve",
    watch:"Keputusan suku bunga + statement + dot plot (tiap meeting ke-4) + presser Powell 19:30 WIB",
    why:"Penentu arah likuiditas USD global. Hampir semua aset risk-on/off bergerak dari sini.",
    outcomes:["HAWKISH","DOVISH","INLINE"],
    outcomeDesc:{
      HAWKISH:"Hike/hold lebih lama dari ekspektasi, atau nada lebih ketat dari proyeksi pasar",
      DOVISH:"Cut/hold lebih dovish, sinyal pivot, dot plot lebih rendah dari ekspektasi",
      INLINE:"Sesuai ekspektasi, minim kejutan"
    }
  },
  {
    id:"CPI", name:"US CPI (Inflasi)", freq:"Bulanan (~tgl 10-15)",
    time:"19:30 / 20:30 WIB (saat DST)", source:"BLS (Bureau of Labor Statistics)",
    watch:"YoY headline, MoM, dan Core CPI (ex food & energy) — Core lebih penting untuk Fed",
    why:"Data inflasi utama yang dipakai Fed untuk kebijakan moneter. Surprise besar = repricing ekspektasi rate cut/hike.",
    outcomes:["HOT","COOL","INLINE"],
    outcomeDesc:{
      HOT:"Di atas ekspektasi (inflasi lebih panas dari perkiraan)",
      COOL:"Di bawah ekspektasi (inflasi mereda lebih cepat dari perkiraan)",
      INLINE:"Sesuai konsensus"
    }
  },
  {
    id:"NFP", name:"Non-Farm Payrolls (Jobs Report)", freq:"Bulanan (Jumat pertama)",
    time:"19:30 / 20:30 WIB", source:"BLS",
    watch:"Jumlah payroll + Unemployment Rate + Average Hourly Earnings",
    why:"Indikator kekuatan pasar tenaga kerja → proxy kesehatan ekonomi dan tekanan upah/inflasi.",
    outcomes:["STRONG","WEAK","INLINE"],
    outcomeDesc:{
      STRONG:"Payroll jauh di atas ekspektasi & unemployment turun/stabil (ekonomi kuat, Fed bisa lebih hawkish)",
      WEAK:"Payroll jauh di bawah ekspektasi atau unemployment naik (sinyal pelemahan ekonomi → harapan cut)",
      INLINE:"Sesuai ekspektasi"
    }
  },
  {
    id:"PCE", name:"Core PCE Price Index", freq:"Bulanan (akhir bulan)",
    time:"19:30 / 20:30 WIB", source:"BEA",
    watch:"Core PCE YoY & MoM — ukuran inflasi favorit Fed",
    why:"Lebih disukai Fed dibanding CPI untuk menentukan kebijakan, dampak mirip CPI tapi biasanya lebih kalem.",
    outcomes:["HOT","COOL","INLINE"],
    outcomeDesc:{
      HOT:"Di atas ekspektasi",
      COOL:"Di bawah ekspektasi",
      INLINE:"Sesuai konsensus"
    }
  },
  {
    id:"GDP", name:"US GDP (Advance/Prelim/Final)", freq:"Kuartalan",
    time:"19:30 WIB", source:"BEA",
    watch:"QoQ annualized growth rate",
    why:"Snapshot kesehatan ekonomi secara luas; growth tinggi = risk-on tapi juga bisa = inflasi/hawkish jika overheat.",
    outcomes:["STRONG","WEAK","INLINE"],
    outcomeDesc:{
      STRONG:"Growth jauh di atas ekspektasi",
      WEAK:"Growth di bawah ekspektasi / kontraksi",
      INLINE:"Sesuai ekspektasi"
    }
  },
  {
    id:"ISM_MFG", name:"ISM Manufacturing PMI", freq:"Bulanan (hari kerja pertama)",
    time:"21:00 WIB", source:"ISM",
    watch:"Index >50 = ekspansi, <50 = kontraksi. Sub-index: New Orders, Prices Paid",
    why:"Leading indicator aktivitas industri & sentimen bisnis, sering bergerak lebih dulu dari data resmi lain.",
    outcomes:["STRONG","WEAK","INLINE"],
    outcomeDesc:{
      STRONG:"Di atas ekspektasi / makin ekspansif",
      WEAK:"Di bawah ekspektasi / makin kontraksi",
      INLINE:"Sesuai ekspektasi"
    }
  },
  {
    id:"JOBLESS", name:"Initial Jobless Claims", freq:"Mingguan (Kamis)",
    time:"19:30 WIB", source:"DOL",
    watch:"Jumlah klaim pengangguran baru mingguan",
    why:"Indikator real-time kondisi pasar tenaga kerja, sering jadi early warning sebelum NFP.",
    outcomes:["STRONG","WEAK","INLINE"],
    outcomeDesc:{
      STRONG:"Klaim lebih rendah dari ekspektasi (pasar kerja kuat)",
      WEAK:"Klaim lebih tinggi dari ekspektasi (pasar kerja melemah)",
      INLINE:"Sesuai ekspektasi"
    }
  },
  {
    id:"PPI", name:"Producer Price Index (PPI)", freq:"Bulanan",
    time:"19:30 WIB", source:"BLS",
    watch:"YoY & MoM, Core PPI",
    why:"Inflasi di level produsen, leading indicator untuk CPI/PCE bulan berikutnya.",
    outcomes:["HOT","COOL","INLINE"],
    outcomeDesc:{
      HOT:"Di atas ekspektasi",
      COOL:"Di bawah ekspektasi",
      INLINE:"Sesuai konsensus"
    }
  },
  {
    id:"RETAIL", name:"Retail Sales", freq:"Bulanan (~tgl 15)",
    time:"19:30 WIB", source:"Census Bureau",
    watch:"MoM headline & ex-Auto",
    why:"Proxy konsumsi konsumen — ~70% dari PDB AS. Kuat = ekonomi solid, lemah = sinyal slowdown.",
    outcomes:["STRONG","WEAK","INLINE"],
    outcomeDesc:{
      STRONG:"Di atas ekspektasi",
      WEAK:"Di bawah ekspektasi",
      INLINE:"Sesuai konsensus"
    }
  },
  {
    id:"FEDSPEAK", name:"Fed Speaker / Powell Speech", freq:"Sering (mingguan/2x mingguan)",
    time:"Variatif", source:"Federal Reserve officials",
    watch:"Nada komentar terkait inflasi, jobs, dan jalur suku bunga ke depan",
    why:"Pasar sangat sensitif terhadap kata-kata pejabat Fed di luar jadwal FOMC resmi — bisa memicu repricing cepat.",
    outcomes:["HAWKISH","DOVISH","INLINE"],
    outcomeDesc:{
      HAWKISH:"Nada lebih ketat / menahan cut / waspada inflasi",
      DOVISH:"Nada lebih lunak / membuka opsi cut lebih cepat",
      INLINE:"Tidak ada pergeseran nada signifikan"
    }
  },
  {
    id:"GEOPOL", name:"Geopolitical Shock / Risk Event", freq:"Tidak terjadwal",
    time:"Kapan saja", source:"Berita global",
    watch:"Konflik, sanksi, kejutan kebijakan negara besar, krisis bank/likuiditas",
    why:"Shock mendadak memicu flight-to-safety atau flight-to-risk tergantung sifat eventnya.",
    outcomes:["RISKOFF","RISKON"],
    outcomeDesc:{
      RISKOFF:"Shock negatif → pelarian ke aset aman (USD, Gold, JPY, CHF, bonds)",
      RISKON:"Resolusi konflik / de-escalation → kembali ke aset berisiko"
    }
  },
];

// ── SIGNAL DATABASE ──────────────────────────────────────────────────────
// Untuk setiap event.outcome -> daftar {asset, dir, prob, note}
// prob = estimasi probabilitas historis arah ini terjadi (subjektif, basis playbook makro umum)
const SIGNALS = {

FOMC_HAWKISH:[
  {a:"BTC",d:DIR.SHORT,p:78,n:"Likuiditas USD mengetat → risk-off crypto"},
  {a:"ETH",d:DIR.SHORT,p:80,n:"Lebih volatile dari BTC saat risk-off"},
  {a:"ALT",d:DIR.SHORT,p:83,n:"Altcoin paling rentan saat likuiditas ketat"},
  {a:"BTCD",d:DIR.LONG,p:65,n:"Dana lari dari alt ke BTC (flight to relative safety)"},
  {a:"DXY",d:DIR.LONG,p:82,n:"Rate lebih tinggi/lebih lama = USD menguat"},
  {a:"EURUSD",d:DIR.SHORT,p:76,n:"USD kuat tekan EUR"},
  {a:"GBPUSD",d:DIR.SHORT,p:70,n:"Ikut tekanan USD broad"},
  {a:"USDJPY",d:DIR.LONG,p:70,n:"Yield gap AS-Jepang melebar"},
  {a:"AUDUSD",d:DIR.SHORT,p:78,n:"Risk-off currency pertama kena jual"},
  {a:"NZDUSD",d:DIR.SHORT,p:76,n:"Sama seperti AUD, high-beta currency"},
  {a:"USDCAD",d:DIR.LONG,p:65,n:"USD kuat, meski oil bisa redam sebagian"},
  {a:"USDCHF",d:DIR.LONG,p:60,n:"USD kuat vs CHF, walau CHF juga safe haven"},
  {a:"GOLD",d:DIR.SHORT,p:70,n:"Real yield naik + USD kuat tekan gold"},
  {a:"SILVER",d:DIR.SHORT,p:65,n:"Ikut gold, lebih volatile"},
  {a:"OIL",d:DIR.SHORT,p:58,n:"Growth concern + USD kuat"},
  {a:"COPPER",d:DIR.SHORT,p:60,n:"Sensitif ke ekspektasi growth global"},
  {a:"SPX",d:DIR.SHORT,p:73,n:"Discount rate naik tekan valuasi equity"},
  {a:"VIX",d:DIR.LONG,p:72,n:"Volatility naik saat kejutan hawkish"},
  {a:"US10Y",d:DIR.LONG,p:80,n:"Yield naik mengikuti ekspektasi rate path lebih tinggi"},
],
FOMC_DOVISH:[
  {a:"BTC",d:DIR.LONG,p:80,n:"Ekspektasi likuiditas longgar = risk-on"},
  {a:"ETH",d:DIR.LONG,p:82,n:"Amplifikasi rally BTC"},
  {a:"ALT",d:DIR.LONG,p:85,n:"Katalis klasik altcoin season"},
  {a:"BTCD",d:DIR.SHORT,p:60,n:"Dana rotasi ke altcoin saat risk-on"},
  {a:"DXY",d:DIR.SHORT,p:80,n:"Rate lebih rendah/lebih cepat cut = USD lemah"},
  {a:"EURUSD",d:DIR.LONG,p:74,n:"USD lemah angkat EUR"},
  {a:"GBPUSD",d:DIR.LONG,p:70,n:"Ikut pelemahan USD broad"},
  {a:"USDJPY",d:DIR.SHORT,p:68,n:"Yield gap menyempit, JPY menguat"},
  {a:"AUDUSD",d:DIR.LONG,p:78,n:"Risk-on currency diuntungkan"},
  {a:"NZDUSD",d:DIR.LONG,p:76,n:"Sama seperti AUD"},
  {a:"USDCAD",d:DIR.SHORT,p:62,n:"USD lemah, CAD juga terbantu oil"},
  {a:"USDCHF",d:DIR.SHORT,p:60,n:"USD melemah broad"},
  {a:"GOLD",d:DIR.LONG,p:75,n:"Real yield turun = gold favorit klasik"},
  {a:"SILVER",d:DIR.LONG,p:72,n:"Leveraged terhadap gold"},
  {a:"OIL",d:DIR.LONG,p:62,n:"Ekspektasi growth/demand membaik"},
  {a:"COPPER",d:DIR.LONG,p:60,n:"Sentimen growth global membaik"},
  {a:"SPX",d:DIR.LONG,p:78,n:"Rate cut/lower-for-longer dukung valuasi"},
  {a:"VIX",d:DIR.SHORT,p:70,n:"Fear turun, market relief"},
  {a:"US10Y",d:DIR.SHORT,p:78,n:"Yield turun mengikuti ekspektasi rate lebih rendah"},
],
FOMC_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:55,n:"Buy-the-rumor-sell-the-news, minim kejutan"},
  {a:"ETH",d:DIR.NEUTRAL,p:54,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:52,n:""},
  {a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:55,n:"Status quo, range-bound"},
  {a:"EURUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:53,n:""},
  {a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},
  {a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.LONG,p:58,n:"Relief rally minor jika tone tetap balanced"},
  {a:"VIX",d:DIR.SHORT,p:58,n:"Volatility mengendap setelah event"},
  {a:"US10Y",d:DIR.NEUTRAL,p:52,n:""},
],

CPI_HOT:[
  {a:"BTC",d:DIR.SHORT,p:74,n:"Fed bertahan hawkish lebih lama"},
  {a:"ETH",d:DIR.SHORT,p:76,n:"Lebih volatile dari BTC"},
  {a:"ALT",d:DIR.SHORT,p:80,n:"Altcoin paling terpukul saat sentimen risk-off inflasi"},
  {a:"BTCD",d:DIR.LONG,p:60,n:"BTC relatif lebih tahan dibanding alt"},
  {a:"DXY",d:DIR.LONG,p:78,n:"Ekspektasi cut tertunda = USD naik"},
  {a:"EURUSD",d:DIR.SHORT,p:72,n:""},
  {a:"GBPUSD",d:DIR.SHORT,p:68,n:""},
  {a:"USDJPY",d:DIR.LONG,p:68,n:"Yield AS naik, gap melebar"},
  {a:"AUDUSD",d:DIR.SHORT,p:75,n:"Risk-off + USD kuat"},
  {a:"NZDUSD",d:DIR.SHORT,p:73,n:""},
  {a:"USDCAD",d:DIR.LONG,p:60,n:""},
  {a:"USDCHF",d:DIR.LONG,p:58,n:""},
  {a:"GOLD",d:DIR.SHORT,p:64,n:"USD kuat & yield naik tekan gold jangka pendek"},
  {a:"SILVER",d:DIR.SHORT,p:60,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:52,n:"Efek campuran: inflasi vs demand worry"},
  {a:"COPPER",d:DIR.SHORT,p:55,n:""},
  {a:"SPX",d:DIR.SHORT,p:72,n:"Ekspektasi rate path lebih ketat"},
  {a:"VIX",d:DIR.LONG,p:70,n:""},
  {a:"US10Y",d:DIR.LONG,p:78,n:""},
],
CPI_COOL:[
  {a:"BTC",d:DIR.LONG,p:73,n:"Disinflasi membuka jalan pivot"},
  {a:"ETH",d:DIR.LONG,p:75,n:""},
  {a:"ALT",d:DIR.LONG,p:78,n:"Katalis rally altcoin"},
  {a:"BTCD",d:DIR.SHORT,p:58,n:"Rotasi ke alt"},
  {a:"DXY",d:DIR.SHORT,p:75,n:"Jalur cut terbuka lebih cepat"},
  {a:"EURUSD",d:DIR.LONG,p:70,n:""},
  {a:"GBPUSD",d:DIR.LONG,p:66,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:65,n:""},
  {a:"AUDUSD",d:DIR.LONG,p:73,n:"Risk-on + USD lemah"},
  {a:"NZDUSD",d:DIR.LONG,p:71,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:58,n:""},
  {a:"USDCHF",d:DIR.SHORT,p:56,n:""},
  {a:"GOLD",d:DIR.LONG,p:70,n:"Real yield turun"},
  {a:"SILVER",d:DIR.LONG,p:68,n:""},
  {a:"OIL",d:DIR.LONG,p:56,n:"Optimisme growth/soft landing"},
  {a:"COPPER",d:DIR.LONG,p:55,n:""},
  {a:"SPX",d:DIR.LONG,p:72,n:"Rate cut hopes"},
  {a:"VIX",d:DIR.SHORT,p:68,n:""},
  {a:"US10Y",d:DIR.SHORT,p:75,n:""},
],
CPI_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:54,n:"Sebagian besar sudah priced-in"},
  {a:"ETH",d:DIR.NEUTRAL,p:52,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},
  {a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:52,n:""},
  {a:"EURUSD",d:DIR.NEUTRAL,p:51,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:51,n:""},
  {a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"SILVER",d:DIR.NEUTRAL,p:51,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},
  {a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.LONG,p:56,n:"Relief minor (no surprise = good)"},
  {a:"VIX",d:DIR.SHORT,p:55,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:51,n:""},
],

NFP_STRONG:[
  {a:"BTC",d:DIR.SHORT,p:62,n:"Jobs kuat → cut tertunda, sedikit risk-off"},
  {a:"ETH",d:DIR.SHORT,p:63,n:""},
  {a:"ALT",d:DIR.SHORT,p:65,n:""},
  {a:"BTCD",d:DIR.LONG,p:55,n:""},
  {a:"DXY",d:DIR.LONG,p:70,n:"Ekonomi kuat = USD kuat (rate higher-for-longer)"},
  {a:"EURUSD",d:DIR.SHORT,p:65,n:""},
  {a:"GBPUSD",d:DIR.SHORT,p:62,n:""},
  {a:"USDJPY",d:DIR.LONG,p:65,n:""},
  {a:"AUDUSD",d:DIR.SHORT,p:63,n:""},
  {a:"NZDUSD",d:DIR.SHORT,p:62,n:""},
  {a:"USDCAD",d:DIR.LONG,p:58,n:""},
  {a:"USDCHF",d:DIR.LONG,p:55,n:""},
  {a:"GOLD",d:DIR.SHORT,p:60,n:"USD kuat & yield naik tekan gold"},
  {a:"SILVER",d:DIR.SHORT,p:57,n:""},
  {a:"OIL",d:DIR.LONG,p:55,n:"Ekonomi kuat = demand energi naik"},
  {a:"COPPER",d:DIR.LONG,p:56,n:"Sinyal growth positif"},
  {a:"SPX",d:DIR.NEUTRAL,p:53,n:"Efek campuran: good news vs hawkish risk"},
  {a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.LONG,p:68,n:""},
],
NFP_WEAK:[
  {a:"BTC",d:DIR.LONG,p:62,n:"Harapan cut lebih cepat = risk-on"},
  {a:"ETH",d:DIR.LONG,p:63,n:""},
  {a:"ALT",d:DIR.LONG,p:65,n:""},
  {a:"BTCD",d:DIR.SHORT,p:55,n:""},
  {a:"DXY",d:DIR.SHORT,p:68,n:"Ekspektasi cut naik = USD lemah"},
  {a:"EURUSD",d:DIR.LONG,p:64,n:""},
  {a:"GBPUSD",d:DIR.LONG,p:61,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:62,n:""},
  {a:"AUDUSD",d:DIR.LONG,p:60,n:""},
  {a:"NZDUSD",d:DIR.LONG,p:59,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:56,n:""},
  {a:"USDCHF",d:DIR.SHORT,p:54,n:""},
  {a:"GOLD",d:DIR.LONG,p:65,n:"Cut hopes naik, real yield turun"},
  {a:"SILVER",d:DIR.LONG,p:62,n:""},
  {a:"OIL",d:DIR.SHORT,p:55,n:"Sinyal pelemahan ekonomi → demand worry"},
  {a:"COPPER",d:DIR.SHORT,p:56,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:52,n:"Efek campuran: bad news vs dovish hopes"},
  {a:"VIX",d:DIR.LONG,p:58,n:"Kekhawatiran resesi bisa naikkan vol"},
  {a:"US10Y",d:DIR.SHORT,p:66,n:""},
],
NFP_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:52,n:""},{a:"ETH",d:DIR.NEUTRAL,p:51,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:51,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:51,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:51,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

PCE_HOT:[
  {a:"BTC",d:DIR.SHORT,p:68,n:"Inflasi gauge favorit Fed panas → hawkish risk"},
  {a:"ETH",d:DIR.SHORT,p:70,n:""},
  {a:"ALT",d:DIR.SHORT,p:73,n:""},
  {a:"BTCD",d:DIR.LONG,p:58,n:""},
  {a:"DXY",d:DIR.LONG,p:73,n:""},
  {a:"EURUSD",d:DIR.SHORT,p:68,n:""},
  {a:"GBPUSD",d:DIR.SHORT,p:64,n:""},
  {a:"USDJPY",d:DIR.LONG,p:64,n:""},
  {a:"AUDUSD",d:DIR.SHORT,p:70,n:""},
  {a:"NZDUSD",d:DIR.SHORT,p:68,n:""},
  {a:"USDCAD",d:DIR.LONG,p:58,n:""},
  {a:"USDCHF",d:DIR.LONG,p:56,n:""},
  {a:"GOLD",d:DIR.SHORT,p:62,n:""},
  {a:"SILVER",d:DIR.SHORT,p:58,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:51,n:""},
  {a:"COPPER",d:DIR.SHORT,p:53,n:""},
  {a:"SPX",d:DIR.SHORT,p:68,n:""},
  {a:"VIX",d:DIR.LONG,p:65,n:""},
  {a:"US10Y",d:DIR.LONG,p:73,n:""},
],
PCE_COOL:[
  {a:"BTC",d:DIR.LONG,p:68,n:"Pivot hopes naik"},
  {a:"ETH",d:DIR.LONG,p:70,n:""},
  {a:"ALT",d:DIR.LONG,p:73,n:""},
  {a:"BTCD",d:DIR.SHORT,p:56,n:""},
  {a:"DXY",d:DIR.SHORT,p:72,n:""},
  {a:"EURUSD",d:DIR.LONG,p:67,n:""},
  {a:"GBPUSD",d:DIR.LONG,p:63,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:62,n:""},
  {a:"AUDUSD",d:DIR.LONG,p:69,n:""},
  {a:"NZDUSD",d:DIR.LONG,p:67,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:56,n:""},
  {a:"USDCHF",d:DIR.SHORT,p:54,n:""},
  {a:"GOLD",d:DIR.LONG,p:68,n:""},
  {a:"SILVER",d:DIR.LONG,p:65,n:""},
  {a:"OIL",d:DIR.LONG,p:53,n:""},
  {a:"COPPER",d:DIR.LONG,p:53,n:""},
  {a:"SPX",d:DIR.LONG,p:68,n:""},
  {a:"VIX",d:DIR.SHORT,p:65,n:""},
  {a:"US10Y",d:DIR.SHORT,p:72,n:""},
],
PCE_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:52,n:""},{a:"ETH",d:DIR.NEUTRAL,p:51,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:51,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:51,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:51,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

GDP_STRONG:[
  {a:"BTC",d:DIR.NEUTRAL,p:53,n:"Efek campuran: optimisme vs risiko hawkish"},
  {a:"ETH",d:DIR.NEUTRAL,p:52,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},
  {a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.LONG,p:65,n:"Ekonomi solid mendukung USD"},
  {a:"EURUSD",d:DIR.SHORT,p:60,n:""},
  {a:"GBPUSD",d:DIR.SHORT,p:57,n:""},
  {a:"USDJPY",d:DIR.LONG,p:60,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"NZDUSD",d:DIR.NEUTRAL,p:51,n:""},
  {a:"USDCAD",d:DIR.LONG,p:55,n:""},
  {a:"USDCHF",d:DIR.LONG,p:53,n:""},
  {a:"GOLD",d:DIR.SHORT,p:55,n:""},
  {a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.LONG,p:60,n:"Demand outlook membaik"},
  {a:"COPPER",d:DIR.LONG,p:62,n:"Growth proxy klasik"},
  {a:"SPX",d:DIR.LONG,p:62,n:"Earnings outlook membaik"},
  {a:"VIX",d:DIR.SHORT,p:58,n:""},
  {a:"US10Y",d:DIR.LONG,p:60,n:""},
],
GDP_WEAK:[
  {a:"BTC",d:DIR.NEUTRAL,p:53,n:"Efek campuran: risk-off vs dovish hopes"},
  {a:"ETH",d:DIR.NEUTRAL,p:52,n:""},
  {a:"ALT",d:DIR.SHORT,p:55,n:""},
  {a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:53,n:"Efek campuran: safe haven vs dovish"},
  {a:"EURUSD",d:DIR.NEUTRAL,p:51,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:58,n:"JPY safe haven saat growth worry"},
  {a:"AUDUSD",d:DIR.SHORT,p:60,n:"Risk-off currency"},
  {a:"NZDUSD",d:DIR.SHORT,p:58,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:51,n:""},
  {a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.LONG,p:62,n:"Safe haven + cut hopes"},
  {a:"SILVER",d:DIR.NEUTRAL,p:53,n:""},
  {a:"OIL",d:DIR.SHORT,p:62,n:"Demand outlook memburuk"},
  {a:"COPPER",d:DIR.SHORT,p:63,n:"Growth proxy turun"},
  {a:"SPX",d:DIR.SHORT,p:60,n:"Earnings outlook memburuk"},
  {a:"VIX",d:DIR.LONG,p:62,n:""},
  {a:"US10Y",d:DIR.SHORT,p:58,n:"Flight to safety bonds"},
],
GDP_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:51,n:""},{a:"ETH",d:DIR.NEUTRAL,p:50,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:50,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:50,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:50,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

ISM_MFG_STRONG:[
  {a:"BTC",d:DIR.NEUTRAL,p:52,n:""},{a:"ETH",d:DIR.NEUTRAL,p:51,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.LONG,p:60,n:"Aktivitas industri kuat dukung USD"},
  {a:"EURUSD",d:DIR.SHORT,p:56,n:""},{a:"GBPUSD",d:DIR.SHORT,p:54,n:""},
  {a:"USDJPY",d:DIR.LONG,p:56,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:53,n:"AUD sensitif manufacturing global juga"},
  {a:"NZDUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:52,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:51,n:""},
  {a:"GOLD",d:DIR.SHORT,p:53,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.LONG,p:60,n:"Demand industri naik"},
  {a:"COPPER",d:DIR.LONG,p:65,n:"Indikator manufacturing langsung terkait copper demand"},
  {a:"SPX",d:DIR.LONG,p:58,n:""},{a:"VIX",d:DIR.SHORT,p:54,n:""},
  {a:"US10Y",d:DIR.LONG,p:56,n:""},
],
ISM_MFG_WEAK:[
  {a:"BTC",d:DIR.NEUTRAL,p:52,n:""},{a:"ETH",d:DIR.NEUTRAL,p:51,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.SHORT,p:56,n:"Sinyal pelemahan ekonomi"},
  {a:"EURUSD",d:DIR.LONG,p:53,n:""},{a:"GBPUSD",d:DIR.NEUTRAL,p:51,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:55,n:"JPY safe haven"},
  {a:"AUDUSD",d:DIR.SHORT,p:56,n:"AUD sensitif manufacturing global"},
  {a:"NZDUSD",d:DIR.SHORT,p:54,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:51,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.LONG,p:58,n:"Growth worry dukung gold"},
  {a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.SHORT,p:60,n:"Demand industri turun"},
  {a:"COPPER",d:DIR.SHORT,p:65,n:""},
  {a:"SPX",d:DIR.SHORT,p:58,n:""},{a:"VIX",d:DIR.LONG,p:56,n:""},
  {a:"US10Y",d:DIR.SHORT,p:55,n:""},
],
ISM_MFG_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:50,n:""},{a:"ETH",d:DIR.NEUTRAL,p:50,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:50,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:50,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:50,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

JOBLESS_STRONG:[ // klaim lebih rendah = pasar kerja kuat (mirip arah NFP_STRONG tapi lebih lemah krn data mingguan)
  {a:"BTC",d:DIR.NEUTRAL,p:53,n:"Data mingguan, dampak lebih kecil dari NFP"},
  {a:"ETH",d:DIR.NEUTRAL,p:52,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.LONG,p:58,n:"Pasar kerja kuat dukung USD"},
  {a:"EURUSD",d:DIR.SHORT,p:55,n:""},{a:"GBPUSD",d:DIR.SHORT,p:53,n:""},
  {a:"USDJPY",d:DIR.LONG,p:55,n:""},
  {a:"AUDUSD",d:DIR.SHORT,p:54,n:""},{a:"NZDUSD",d:DIR.SHORT,p:53,n:""},
  {a:"USDCAD",d:DIR.LONG,p:52,n:""},{a:"USDCHF",d:DIR.LONG,p:51,n:""},
  {a:"GOLD",d:DIR.SHORT,p:54,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:51,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:51,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:52,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.LONG,p:55,n:""},
],
JOBLESS_WEAK:[ // klaim lebih tinggi = pasar kerja melemah
  {a:"BTC",d:DIR.NEUTRAL,p:53,n:"Data mingguan, dampak lebih kecil dari NFP"},
  {a:"ETH",d:DIR.NEUTRAL,p:52,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.SHORT,p:57,n:"Sinyal pelemahan tenaga kerja"},
  {a:"EURUSD",d:DIR.LONG,p:54,n:""},{a:"GBPUSD",d:DIR.LONG,p:52,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:54,n:""},
  {a:"AUDUSD",d:DIR.LONG,p:53,n:""},{a:"NZDUSD",d:DIR.LONG,p:52,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:52,n:""},{a:"USDCHF",d:DIR.SHORT,p:51,n:""},
  {a:"GOLD",d:DIR.LONG,p:58,n:"Cut hopes naik"},{a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:51,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:51,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:51,n:""},{a:"VIX",d:DIR.LONG,p:54,n:""},
  {a:"US10Y",d:DIR.SHORT,p:56,n:""},
],
JOBLESS_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:50,n:""},{a:"ETH",d:DIR.NEUTRAL,p:50,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:50,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:50,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:50,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

PPI_HOT:[
  {a:"BTC",d:DIR.SHORT,p:60,n:"Leading indicator inflasi naik → hawkish risk"},
  {a:"ETH",d:DIR.SHORT,p:61,n:""},
  {a:"ALT",d:DIR.SHORT,p:63,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:53,n:""},
  {a:"DXY",d:DIR.LONG,p:64,n:""},
  {a:"EURUSD",d:DIR.SHORT,p:60,n:""},{a:"GBPUSD",d:DIR.SHORT,p:57,n:""},
  {a:"USDJPY",d:DIR.LONG,p:58,n:""},
  {a:"AUDUSD",d:DIR.SHORT,p:60,n:""},{a:"NZDUSD",d:DIR.SHORT,p:58,n:""},
  {a:"USDCAD",d:DIR.LONG,p:54,n:""},{a:"USDCHF",d:DIR.LONG,p:53,n:""},
  {a:"GOLD",d:DIR.SHORT,p:56,n:""},{a:"SILVER",d:DIR.SHORT,p:53,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:52,n:"PPI sering didorong harga energi itu sendiri"},
  {a:"COPPER",d:DIR.NEUTRAL,p:51,n:""},
  {a:"SPX",d:DIR.SHORT,p:60,n:""},{a:"VIX",d:DIR.LONG,p:57,n:""},
  {a:"US10Y",d:DIR.LONG,p:62,n:""},
],
PPI_COOL:[
  {a:"BTC",d:DIR.LONG,p:60,n:"Sinyal disinflasi lanjutan"},
  {a:"ETH",d:DIR.LONG,p:61,n:""},
  {a:"ALT",d:DIR.LONG,p:63,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:53,n:""},
  {a:"DXY",d:DIR.SHORT,p:63,n:""},
  {a:"EURUSD",d:DIR.LONG,p:59,n:""},{a:"GBPUSD",d:DIR.LONG,p:56,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:57,n:""},
  {a:"AUDUSD",d:DIR.LONG,p:59,n:""},{a:"NZDUSD",d:DIR.LONG,p:57,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:53,n:""},{a:"USDCHF",d:DIR.SHORT,p:52,n:""},
  {a:"GOLD",d:DIR.LONG,p:60,n:""},{a:"SILVER",d:DIR.LONG,p:57,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:51,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:51,n:""},
  {a:"SPX",d:DIR.LONG,p:60,n:""},{a:"VIX",d:DIR.SHORT,p:56,n:""},
  {a:"US10Y",d:DIR.SHORT,p:62,n:""},
],
PPI_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:50,n:""},{a:"ETH",d:DIR.NEUTRAL,p:50,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:50,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:50,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:50,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

RETAIL_STRONG:[
  {a:"BTC",d:DIR.NEUTRAL,p:52,n:"Konsumsi kuat: efek campuran growth vs hawkish"},
  {a:"ETH",d:DIR.NEUTRAL,p:51,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:51,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.LONG,p:62,n:"Konsumsi kuat dukung USD & ekspektasi rate"},
  {a:"EURUSD",d:DIR.SHORT,p:57,n:""},{a:"GBPUSD",d:DIR.SHORT,p:55,n:""},
  {a:"USDJPY",d:DIR.LONG,p:57,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:53,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:52,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:51,n:""},
  {a:"GOLD",d:DIR.SHORT,p:55,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.LONG,p:56,n:"Demand konsumen membaik"},
  {a:"COPPER",d:DIR.LONG,p:55,n:""},
  {a:"SPX",d:DIR.LONG,p:60,n:"Konsumsi = mesin ekonomi AS"},
  {a:"VIX",d:DIR.SHORT,p:55,n:""},{a:"US10Y",d:DIR.LONG,p:58,n:""},
],
RETAIL_WEAK:[
  {a:"BTC",d:DIR.NEUTRAL,p:52,n:"Efek campuran: growth worry vs dovish hopes"},
  {a:"ETH",d:DIR.NEUTRAL,p:51,n:""},
  {a:"ALT",d:DIR.SHORT,p:54,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.SHORT,p:58,n:"Konsumsi lemah = sinyal slowdown"},
  {a:"EURUSD",d:DIR.NEUTRAL,p:53,n:""},{a:"GBPUSD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:55,n:"JPY safe haven"},
  {a:"AUDUSD",d:DIR.SHORT,p:55,n:"Risk-off"},{a:"NZDUSD",d:DIR.SHORT,p:54,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:51,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.LONG,p:58,n:"Cut hopes + safe haven"},{a:"SILVER",d:DIR.NEUTRAL,p:52,n:""},
  {a:"OIL",d:DIR.SHORT,p:58,n:"Demand konsumen melemah"},
  {a:"COPPER",d:DIR.SHORT,p:55,n:""},
  {a:"SPX",d:DIR.SHORT,p:60,n:"Konsumsi melemah = earnings risk"},
  {a:"VIX",d:DIR.LONG,p:58,n:""},{a:"US10Y",d:DIR.SHORT,p:56,n:""},
],
RETAIL_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:50,n:""},{a:"ETH",d:DIR.NEUTRAL,p:50,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:50,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:50,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:50,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

FEDSPEAK_HAWKISH:[
  {a:"BTC",d:DIR.SHORT,p:68,n:"Repricing cepat ke arah hawkish"},
  {a:"ETH",d:DIR.SHORT,p:70,n:""},
  {a:"ALT",d:DIR.SHORT,p:73,n:""},{a:"BTCD",d:DIR.LONG,p:58,n:""},
  {a:"DXY",d:DIR.LONG,p:72,n:""},
  {a:"EURUSD",d:DIR.SHORT,p:66,n:""},{a:"GBPUSD",d:DIR.SHORT,p:62,n:""},
  {a:"USDJPY",d:DIR.LONG,p:62,n:""},
  {a:"AUDUSD",d:DIR.SHORT,p:68,n:""},{a:"NZDUSD",d:DIR.SHORT,p:66,n:""},
  {a:"USDCAD",d:DIR.LONG,p:56,n:""},{a:"USDCHF",d:DIR.LONG,p:54,n:""},
  {a:"GOLD",d:DIR.SHORT,p:62,n:""},{a:"SILVER",d:DIR.SHORT,p:58,n:""},
  {a:"OIL",d:DIR.SHORT,p:53,n:""},{a:"COPPER",d:DIR.SHORT,p:54,n:""},
  {a:"SPX",d:DIR.SHORT,p:65,n:""},{a:"VIX",d:DIR.LONG,p:64,n:""},
  {a:"US10Y",d:DIR.LONG,p:70,n:""},
],
FEDSPEAK_DOVISH:[
  {a:"BTC",d:DIR.LONG,p:68,n:"Repricing cepat ke arah dovish"},
  {a:"ETH",d:DIR.LONG,p:70,n:""},
  {a:"ALT",d:DIR.LONG,p:73,n:""},{a:"BTCD",d:DIR.SHORT,p:56,n:""},
  {a:"DXY",d:DIR.SHORT,p:70,n:""},
  {a:"EURUSD",d:DIR.LONG,p:64,n:""},{a:"GBPUSD",d:DIR.LONG,p:60,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:60,n:""},
  {a:"AUDUSD",d:DIR.LONG,p:66,n:""},{a:"NZDUSD",d:DIR.LONG,p:64,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:54,n:""},{a:"USDCHF",d:DIR.SHORT,p:52,n:""},
  {a:"GOLD",d:DIR.LONG,p:62,n:""},{a:"SILVER",d:DIR.LONG,p:58,n:""},
  {a:"OIL",d:DIR.LONG,p:54,n:""},{a:"COPPER",d:DIR.LONG,p:54,n:""},
  {a:"SPX",d:DIR.LONG,p:65,n:""},{a:"VIX",d:DIR.SHORT,p:62,n:""},
  {a:"US10Y",d:DIR.SHORT,p:68,n:""},
],
FEDSPEAK_INLINE:[
  {a:"BTC",d:DIR.NEUTRAL,p:50,n:""},{a:"ETH",d:DIR.NEUTRAL,p:50,n:""},
  {a:"ALT",d:DIR.NEUTRAL,p:50,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"DXY",d:DIR.NEUTRAL,p:50,n:""},{a:"EURUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GBPUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDJPY",d:DIR.NEUTRAL,p:50,n:""},
  {a:"AUDUSD",d:DIR.NEUTRAL,p:50,n:""},{a:"NZDUSD",d:DIR.NEUTRAL,p:50,n:""},
  {a:"USDCAD",d:DIR.NEUTRAL,p:50,n:""},{a:"USDCHF",d:DIR.NEUTRAL,p:50,n:""},
  {a:"GOLD",d:DIR.NEUTRAL,p:50,n:""},{a:"SILVER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:50,n:""},{a:"COPPER",d:DIR.NEUTRAL,p:50,n:""},
  {a:"SPX",d:DIR.NEUTRAL,p:50,n:""},{a:"VIX",d:DIR.NEUTRAL,p:50,n:""},
  {a:"US10Y",d:DIR.NEUTRAL,p:50,n:""},
],

GEOPOL_RISKOFF:[
  {a:"BTC",d:DIR.SHORT,p:65,n:"Awalnya ikut risk-off, walau makin sering decouple"},
  {a:"ETH",d:DIR.SHORT,p:68,n:""},
  {a:"ALT",d:DIR.SHORT,p:72,n:""},{a:"BTCD",d:DIR.LONG,p:60,n:""},
  {a:"DXY",d:DIR.LONG,p:75,n:"USD = safe haven utama"},
  {a:"EURUSD",d:DIR.SHORT,p:65,n:""},{a:"GBPUSD",d:DIR.SHORT,p:62,n:""},
  {a:"USDJPY",d:DIR.SHORT,p:60,n:"JPY juga safe haven, kadang menang vs USD"},
  {a:"AUDUSD",d:DIR.SHORT,p:75,n:"Risk currency pertama dijual"},
  {a:"NZDUSD",d:DIR.SHORT,p:73,n:""},
  {a:"USDCAD",d:DIR.LONG,p:60,n:""},
  {a:"USDCHF",d:DIR.SHORT,p:58,n:"CHF safe haven, sering menguat vs USD juga"},
  {a:"GOLD",d:DIR.LONG,p:82,n:"Safe haven klasik #1"},
  {a:"SILVER",d:DIR.LONG,p:65,n:"Ikut gold, tapi industrial demand bisa redam"},
  {a:"OIL",d:DIR.LONG,p:60,n:"Jika konflik di area produsen energi; bisa juga turun jika demand shock"},
  {a:"COPPER",d:DIR.SHORT,p:60,n:"Growth proxy turun saat risk-off"},
  {a:"SPX",d:DIR.SHORT,p:70,n:""},
  {a:"VIX",d:DIR.LONG,p:80,n:"Spike volatility klasik"},
  {a:"US10Y",d:DIR.SHORT,p:70,n:"Flight to bonds (yield turun, harga naik)"},
],
GEOPOL_RISKON:[
  {a:"BTC",d:DIR.LONG,p:60,n:"De-escalation memicu relief rally risk asset"},
  {a:"ETH",d:DIR.LONG,p:62,n:""},
  {a:"ALT",d:DIR.LONG,p:65,n:""},{a:"BTCD",d:DIR.NEUTRAL,p:52,n:""},
  {a:"DXY",d:DIR.SHORT,p:62,n:"Demand safe haven USD turun"},
  {a:"EURUSD",d:DIR.LONG,p:58,n:""},{a:"GBPUSD",d:DIR.LONG,p:56,n:""},
  {a:"USDJPY",d:DIR.LONG,p:55,n:"Unwind dari JPY safe haven"},
  {a:"AUDUSD",d:DIR.LONG,p:68,n:""},{a:"NZDUSD",d:DIR.LONG,p:66,n:""},
  {a:"USDCAD",d:DIR.SHORT,p:55,n:""},{a:"USDCHF",d:DIR.LONG,p:54,n:"Unwind dari CHF safe haven"},
  {a:"GOLD",d:DIR.SHORT,p:70,n:"Demand safe haven mereda"},
  {a:"SILVER",d:DIR.SHORT,p:55,n:""},
  {a:"OIL",d:DIR.NEUTRAL,p:52,n:"Tergantung jenis konflik yang mereda"},
  {a:"COPPER",d:DIR.LONG,p:58,n:""},
  {a:"SPX",d:DIR.LONG,p:68,n:""},
  {a:"VIX",d:DIR.SHORT,p:75,n:"Volatility mengendap"},
  {a:"US10Y",d:DIR.LONG,p:60,n:"Yield naik, harga bond turun"},
],

};

// ── INTER-ASSET STATIC CORRELATION MATRIX ────────────────────────────────
// Korelasi historis umum antar aset (skala -1 s/d +1, basis hubungan makro
// yang sudah dikenal luas, BUKAN dihitung dari data live).
// strength label: VS = very strong, S = strong, M = moderate, W = weak, N = negligible
const CORR_PAIRS = [
  // Crypto internal
  {a:"BTC", b:"ETH",    v: 0.90, note:"ETH umumnya bergerak satu arah dengan BTC, beta lebih tinggi"},
  {a:"BTC", b:"ALT",    v: 0.80, note:"Altcoin mengikuti arah BTC dengan amplitudo lebih besar"},
  {a:"ETH", b:"ALT",    v: 0.85, note:"ETH sering jadi leading indicator untuk altcoin season"},
  {a:"BTC", b:"BTCD",   v: -0.55,note:"Saat BTC melemah relatif lambat dibanding alt, BTC.D naik (inverse terhadap risk-on alt)"},
  {a:"ALT", b:"BTCD",   v: -0.75,note:"Altcoin season = BTC.D turun, dan sebaliknya"},

  // Crypto vs Macro risk proxies
  {a:"BTC", b:"SPX",    v: 0.55, note:"Korelasi moderat-kuat terutama saat regime risk-off besar (mis. 2022)"},
  {a:"BTC", b:"VIX",    v: -0.45,note:"VIX naik tajam biasanya bertepatan BTC turun (risk-off)"},
  {a:"BTC", b:"DXY",    v: -0.55,note:"USD kuat cenderung menekan BTC, terutama saat liquidity tightening"},
  {a:"BTC", b:"GOLD",   v: 0.20, note:"Korelasi lemah & tidak stabil — BTC kadang 'digital gold', kadang risk asset"},
  {a:"BTC", b:"US10Y",  v: -0.35,note:"Yield naik tajam = tekanan ke aset growth/risk termasuk crypto"},

  // DXY relationships
  {a:"DXY", b:"EURUSD", v: -0.98,note:"EUR adalah komponen terbesar DXY basket — hampir mirror terbalik"},
  {a:"DXY", b:"GBPUSD", v: -0.85,note:"Korelasi negatif sangat kuat, GBP komponen besar DXY"},
  {a:"DXY", b:"AUDUSD", v: -0.75,note:"AUD bukan komponen DXY tapi sangat sensitif terhadap arah USD broad"},
  {a:"DXY", b:"NZDUSD", v: -0.72,note:"Mirip AUD, high-beta terhadap USD"},
  {a:"DXY", b:"USDJPY", v: 0.70, note:"USD kuat umumnya = USDJPY naik (meski JPY punya driver sendiri/yield gap)"},
  {a:"DXY", b:"USDCHF", v: 0.65, note:"USD kuat = USDCHF naik, tapi CHF safe-haven bisa melawan tren saat risk-off"},
  {a:"DXY", b:"USDCAD", v: 0.55, note:"USD kuat = USDCAD naik, namun oil price bisa meredam korelasi ini"},
  {a:"DXY", b:"GOLD",   v: -0.70,note:"USD kuat menekan harga gold (gold dihargai dalam USD)"},
  {a:"DXY", b:"BTC",    v: -0.55,note:"Lihat catatan BTC vs DXY"},

  // Gold relationships
  {a:"GOLD", b:"SILVER",v: 0.85, note:"Silver bergerak searah gold dengan volatilitas lebih tinggi ('gold on steroids')"},
  {a:"GOLD", b:"US10Y", v: -0.60,note:"Yield riil naik = opportunity cost pegang gold naik = gold tertekan"},
  {a:"GOLD", b:"VIX",   v: 0.35, note:"Saat fear spike besar, gold sering ikut naik sebagai safe haven (korelasi tidak selalu konsisten)"},
  {a:"GOLD", b:"USDJPY",v: -0.40,note:"Saat risk-off, JPY & gold sering menguat bersamaan (USDJPY turun)"},

  // Oil & growth proxies
  {a:"OIL", b:"USDCAD", v: -0.65,note:"Oil naik = CAD menguat (CAD = petrocurrency) → USDCAD turun"},
  {a:"OIL", b:"COPPER", v: 0.60, note:"Sama-sama proxy demand industri/growth global"},
  {a:"OIL", b:"SPX",    v: 0.40, note:"Korelasi moderat searah growth-driven, tapi bisa terbalik saat oil spike karena supply shock"},
  {a:"COPPER", b:"AUDUSD", v: 0.60, note:"AUD = currency komoditas, sensitif terhadap harga base metals/China demand"},

  // Equity / Vol / Bonds
  {a:"SPX", b:"VIX",    v: -0.80,note:"Hubungan inverse klasik — VIX = 'fear gauge' dari SPX"},
  {a:"SPX", b:"US10Y",  v: -0.30,note:"Kenaikan yield tajam & cepat biasanya tekan valuasi equity (terutama growth/tech)"},
  {a:"US10Y", b:"USDJPY",v: 0.75,note:"Yield gap AS-Jepang adalah driver utama USDJPY"},
  {a:"VIX", b:"AUDUSD", v: -0.60,note:"AUD = risk barometer, bergerak inverse terhadap fear index"},
  {a:"VIX", b:"USDJPY", v: -0.45,note:"Saat fear naik, JPY menguat (carry trade unwind) → USDJPY turun"},

  // JPY cross dynamics
  {a:"USDJPY", b:"AUDUSD", v: 0.30, note:"Keduanya sensitif terhadap risk sentiment global, tapi arah JPY vs AUD vs USD bisa kompleks"},
  {a:"EURUSD", b:"GBPUSD", v: 0.85, note:"Dua mata uang Eropa besar, sering bergerak satu arah terhadap USD"},
  {a:"AUDUSD", b:"NZDUSD", v: 0.90, note:"Antipodean currencies — hampir selalu bergerak bersama"},
];

// helper untuk label kekuatan korelasi
function corrStrength(v){
  const av = Math.abs(v);
  if(av >= 0.85) return {label:"Sangat Kuat", cls:"vs"};
  if(av >= 0.65) return {label:"Kuat", cls:"s"};
  if(av >= 0.40) return {label:"Sedang", cls:"m"};
  if(av >= 0.20) return {label:"Lemah", cls:"w"};
  return {label:"Diabaikan", cls:"n"};
}
